### ISSUE TITLE
Is this possible to use with Seurat objects? 

### ISSUE THREAD

**Issue by ahdee** [Jinsl-lab/scInt#1]
Hi, I'm looking for an algorithm to properly integrate 4 multiome objects I haves stored in seurat. At the moment both harmony and  anchoring has failed to properly integrate but I would like to keep everything in seurat if possible. thanks in advance.

**Comment by Jinsl-lab** [comment]
Hi, it can be done. If you have a Seurat object called seurat.obj already normalized and a vector called vargs that contains the selected features, you can run the scInt integration with the following codes.
```R
library(scInt)
library(Seurat)

dataset = lapply(SplitObject(seurat.obj, split.by = "batchlb"), function(x) x@assays[["RNA"]]@data)
data = create.scInt(dataset, filter = F)
data = ident.cellIdentity(data, vargenes = vargs)
data = compute.Similarity(data)
data = run.Integrate(data)

seurat.obj[["scInt"]] = Seurat::CreateDimReducObject(embeddings = t(data@integrated.data), key = "scInt_", assay = "RNA")
```
I wish the tool worked on your analysis.

**Comment by ahdee** [comment]
@Jinsl-lab great thanks. I'm a bit confused should `vargenes = vargs` is this just the list of all the genes in my object? Also for normalized counts should I use the SCT assay instead? thanks.

**Comment by Jinsl-lab** [comment]
> @Jinsl-lab great thanks. I'm a bit confused should `vargenes = vargs` is this just the list of all the genes in my object? Also for normalized counts should I use the SCT assay instead? thanks.

@ahdee The vargenes depend on your actual data. For scRNA-seq data and scATAC-seq data, we usually want to be able to vargenes are a subset of genes with high variability across all cells (can also be identified use FindVariableFeatures function in Seurat package). For ADT data, because the data dimension is relatively low, we can set vargenes to all genes. And for normalized counts, you can of course use the SCT assay.

**Comment by shiyw** [comment]
In my case (Seurat v5), the above code fails, even when I add `normalize.Data(data)`, with error message indicating normalized data not exist. An inspect of the code shows in `ident.cellIdentity` several Seurat objects are created without `NormalizeData`. A call of `normalize.Data`  won't help since when creating those Seurat objects the first argument is treated as counts even if they are (in fact) normalized data from `object@norm.data`.

I am not sure if this is a true incompatibility issue (or maybe I missed something). If it is, it is simple to fix (hope it will be fixed soon so that we can use it without hacking). If it isn't, please let me know what I missed.

Thanks for your reading and effort making this integration method

**Comment by Jinsl-lab** [comment]
> In my case (Seurat v5), the above code fails, even when I add `normalize.Data(data)`, with error message indicating normalized data not exist. An inspect of the code shows in `ident.cellIdentity` several Seurat objects are created without `NormalizeData`. A call of `normalize.Data` won't help since when creating those Seurat objects the first argument is treated as counts even if they are (in fact) normalized data from `object@norm.data`.
> 
> I am not sure if this is a true incompatibility issue (or maybe I missed something). If it is, it is simple to fix (hope it will be fixed soon so that we can use it without hacking). If it isn't, please let me know what I missed.
> 
> Thanks for your reading and effort making this integration method

Hi, I have modified the codes, and the method is adapted to the Seurat v5 now. If you have any further problems with this package, don't hesitate to get in touch with me.

**Comment by shiyw** [comment]
Many thanks. I will definitely try it out again soon. A nice integration method is very important (although no silver bullet applies here too). Wish this work can be widely used (and cited).

________________________________
发件人: Jinsl-lab ***@***.***>
发送时间: 2024年8月13日 16:21
收件人: Jinsl-lab/scInt ***@***.***>
抄送: shiyw ***@***.***>; Comment ***@***.***>
主题: Re: [Jinsl-lab/scInt] Is this possible to use with Seurat objects? (Issue #1)


In my case (Seurat v5), the above code fails, even when I add normalize.Data(data), with error message indicating normalized data not exist. An inspect of the code shows in ident.cellIdentity several Seurat objects are created without NormalizeData. A call of normalize.Data won't help since when creating those Seurat objects the first argument is treated as counts even if they are (in fact) normalized data from ***@***.***

I am not sure if this is a true incompatibility issue (or maybe I missed something). If it is, it is simple to fix (hope it will be fixed soon so that we can use it without hacking). If it isn't, please let me know what I missed.

Thanks for your reading and effort making this integration method

Hi, I have modified the codes, and the method is adapted to the Seurat v5 now. If you have any further problems with this package, don't hesitate to get in touch with me.

―
